export const ALL_SKILLS = {
  regeneration: {
    key: "regeneration",
    name: "Tự Hồi Phục",
    prop: "dhh:skill_regen",
    max: 9,
    desc: "Tăng hiệu ứng Hồi Máu (Regeneration)",
  },
  ironSkin: {
    key: "ironSkin",
    name: "Da Sắt",
    prop: "dhh:skill_iron",
    max: 7,
    desc: "Tăng hiệu ứng Kháng Sát Thương (Resistance)",
  },
  radar: {
    key: "radar",
    name: "Rada Thăm Dò",
    prop: "dhh:skill_radar",
    max: 9,
    desc: "Tăng phạm vi phát hiện quái vật.",
  },
  targeted_lightning: {
    key: "targeted_lightning",
    name: "Lôi Vực",
    prop: "dhh:skill_targeted_lightning",
    max: 9,
    desc: "Tăng bán kính vùng ảnh hưởng.",
  },
  golem_punch: {
    key: "golem_punch",
    name: "Cú Đấm Golem",
    prop: "dhh:skill_golem_punch",
    max: 9,
    desc: "Tăng sát thương và phạm vi hất văng.",
  },
  shadowbind: {
    key: "shadowbind",
    name: "Dây Trói Bóng Tối",
    prop: "dhh:skill_shadowbind",
    max: 9,
    desc: "Tăng phạm vi hào quang và phí duy trì.",
  },
  winters_dominion: {
    key: "winters_dominion",
    name: "Lãnh Địa Mùa Đông",
    prop: "dhh:skill_winters_dominion",
    max: 9,
    desc: "Tăng thời gian và bán kính hiệu lực.",
  },
  earthen_grave: {
    key: "earthen_grave",
    name: "Mộ Phần Trói Buộc",
    prop: "dhh:skill_earthen_grave",
    max: 9,
    desc: "Tăng thời gian, số mục tiêu và phạm vi.",
  },
  hellfire_pit: {
    key: "hellfire_pit",
    name: "Vực Lửa Địa Ngục",
    prop: "dhh:skill_hellfire_pit",
    max: 9,
    desc: "Tăng bán kính và số mục tiêu hút vào.",
  },
  reality_warp: {
    key: "reality_warp",
    name: "Vùng Hỗn Loạn",
    prop: "dhh:skill_reality_warp",
    max: 9,
    desc: "Gây hiệu ứng hỗn loạn ngẫu nhiên.",
  },
  time_lock: {
    key: "time_lock",
    name: "Giam Cầm Thời Gian",
    prop: "dhh:skill_time_lock",
    max: 9,
    desc: "Tăng bán kính và thời gian hiệu lực.",
  },
  stealth: {
    key: "stealth",
    name: "Tàng Hình",
    prop: "dhh:skill_stealth",
    max: 9,
    desc: "Tăng thời gian tàng hình.",
  },
  heal: {
    key: "heal",
    name: "Chữa Lành",
    prop: "dhh:skill_heal",
    max: 9,
    desc: "Tăng phạm vi và lượng máu hồi phục.",
  },
  dash: {
    key: "dash",
    name: "Lướt Đi",
    prop: "dhh:skill_dash",
    max: 9,
    desc: "Tăng khoảng cách lướt.",
  },
  summon_wolf: {
    key: "summon_wolf",
    name: "Triệu Hồi Linh Thú",
    prop: "dhh:skill_summon_wolf",
    max: 9,
    desc: "Tăng sức mạnh cho Linh Thú.",
  },
  shadow_swap: {
    key: "shadow_swap",
    name: "Thiên Mệnh Thời Không",
    prop: "dhh:skill_shadow_swap",
    max: 9,
    desc: "Tăng thời gian để tái kích hoạt.",
  },
  sprint: {
    key: "sprint",
    name: "Bứt Tốc",
    prop: "dhh:skill_sprint",
    max: 9,
    desc: "Tăng thời gian hiệu lực.",
  },
  ally_swap: {
    key: "ally_swap",
    name: "Thiên Can Hộ Mệnh",
    prop: "dhh:skill_ally_swap",
    max: 9,
    desc: "Nâng cấp phạm vi và khả năng.",
  },
  spirit_sight: {
    key: "spirit_sight",
    name: "Thị Kiến Tâm Linh",
    prop: "dhh:skill_spirit_sight",
    max: 9,
    desc: "Kết nối tâm trí, nhìn qua mắt đồng minh.",
  },
  chaos_trap: {
    key: "chaos_trap",
    name: "Bẫy Hỗn Mang",
    prop: "dhh:skill_chaos_trap",
    max: 9,
    desc: "Tăng số lượng bẫy tối đa có thể đặt cùng lúc.",
  },
  immortal_edict: {
    key: "immortal_edict",
    name: "Thánh Lệnh Bất Diệt",
    prop: "dhh:skill_immortal_edict",
    max: 9,
    desc: "Tăng bán kính hiệu lực và giảm máu tiêu hao.",
  },
  explosion: {
    key: "explosion",
    name: "Bộc Liệt Ma Pháp",
    prop: "dhh:skill_explosion",
    max: 9,
    desc: "Tăng sát thương, phạm vi vụ nổ, giảm thời gian hiệu ứng.",
  },
  blade_storm: {
    key: "blade_storm",
    name: "Bão Kiếm",
    prop: "dhh:skill_blade_storm",
    max: 9,
    desc: "Tăng sát thương, bán kính và thời gian hiệu lực.",
  },
  primal_beast: {
    key: "primal_beast",
    name: "Hóa Thân Thần Thú",
    prop: "dhh:skill_primal_beast",
    max: 9,
    desc: "Tăng thời gian biến hình và sức mạnh nội tại.",
  },
  celestial_step: {
    key: "celestial_step",
    name: "Bước Chân Thiên Giới",
    prop: "dhh:skill_celestial_step",
    max: 9,
    desc: "Tăng số lần và thời gian bay.",
  },
  void_step: {
    key: "void_step",
    name: "Vô Hạ Hạn",
    prop: "dhh:skill_void_step",
    max: 9,
    desc: "Tạo 1 lãnh địa của riêng bạn.",
  },
   life_link: {
    key: "life_link",
    name: "Huyết Mạch Tương Liên",
    prop: "dhh:skill_life_link",
    max: 9,
    desc: "Chuyển % sát thương đồng minh nhận sang bản thân.",
  },
    spatial_link: {
        name: "Liên Kết Chiều Không",
        key: "spatial_link",
        prop: "dhh:skill_spatial_link",
        max: 9,
        desc: "Tạo một cặp cổng dịch chuyển có thể sử dụng.",
    },
};

export const COMMON_SKILLS = ["regeneration", "radar", "ironSkin"];